[master]
34.207.59.241 ansible_user=ubuntu ansible_ssh_private_key_file=labuser.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[workers]
54.167.216.166 ansible_user=ubuntu ansible_ssh_private_key_file=labuser.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
13.217.194.24 ansible_user=ubuntu ansible_ssh_private_key_file=labuser.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
100.58.103.160 ansible_user=ubuntu ansible_ssh_private_key_file=labuser.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'