[master]
100.55.57.35 ansible_user=ubuntu ansible_ssh_private_key_file=labuser.pem

[workers]
3.80.218.207 ansible_user=ubuntu ansible_ssh_private_key_file=labuser.pem
18.205.239.62 ansible_user=ubuntu ansible_ssh_private_key_file=labuser.pem
54.197.37.68 ansible_user=ubuntu ansible_ssh_private_key_file=labuser.pem